# server configuration
server:
  port: 9191

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql:thin://localhost:3306/messagegateway
    username: root
    password: mysql
    driver-class-name: org.drizzle.jdbc.DrizzleDriver
    validation-query: SELECT 1 FROM dual
    max-active: 100
    max-idle: 8
    min-idle: 1
    initial-size: 10
    testOnBorrow: true
    testWhileIdle: true

# Status Callback configuration for Twilio. Port will be taken from server configuration
hostconfig:
  host-address: localhost
  protocol: http
